services:
  web:
    build: ../9ziggy9.web/
    ports:
      - "9002:9002"
  ws:
    build: ../9ziggy9.ws/
    ports:
      - "9003:9003"
  proxy:
    image: nginx:latest
    ports:
      - "9001:9001"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf